# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: [pre-commit, pre-push]

repos:
    # local hooks
    - repo: local
      hooks:
          - id: ruff
            name: ruff
            entry: poetry run ruff check --fix --exit-non-zero-on-fix --show-fixes
            language: system
            types: [python]
            require_serial: true
          - id: mypy
            name: mypy
            entry: poetry run mypy
            language: system
            types: [python]
            files: ^assistant/
            require_serial: true

    # "official" pre-commit hooks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: check-executables-have-shebangs
          - id: check-yaml
          - id: check-json
          - id: check-toml
          - id: check-symlinks

    # third-pary hooks
    - repo: https://github.com/psf/black
      rev: 24.1.1
      hooks:
          - id: black
          - id: black-jupyter
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.7.1
      hooks:
          - id: prettier
    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
          - id: shellcheck
          - id: shfmt
    - repo: https://github.com/kynan/nbstripout
      rev: 0.7.1
      hooks:
          - id: nbstripout
