[tool.poetry]
name = "rag-demo"
version = "0.1.0"
description = "Retrieval-augmented generation assistant demo"
authors = ["Renumics GmbH <info@renumics.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "assistant" },
]

[tool.poetry.scripts]
create-db = "scripts.create_db:app"
answer = "scripts.answer:app"

[tool.poetry.dependencies]
python = "^3.8.1"
langchain = "^0.1.3"
typing-extensions = "^4.9.0"
typer = "^0.9.0"
langchain-openai = "^0.0.3"
langchain-core = "^0.1.15"

[tool.poetry.group.dev.dependencies]
black = "^23.12.1"
ruff = "^0.1.14"
mypy = "^1.7.1"
pre-commit = "^3.0.1"

[tool.mypy]
ignore_missing_imports = false
disallow_untyped_defs = true
explicit_package_bases = true
mypy_path = "."
plugins = "pydantic.mypy"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
