llm_type: 'openai'
llm_name: 'gpt-3.5-turbo'
relevance_score_fn: 'l2'
k: 4
search_type: 'similarity'
score_threshold: 0.5
fetch_k: 20
lambda_mult: 0.5
embeddings_model_type: 'openai'
embeddings_model_name: 'text-embedding-ada-002'
